=== rmlockwood/FLExTrans/XXEaddon/FLExTransTestbedXMLmind/dtds/FLExTransTestbed.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT FLExTransTestbed (testbeds)>
<!ATTLIST FLExTransTestbed source_direction (ltr|rtl) "ltr"
                           target_direction (ltr|rtl) "ltr">

<!ELEMENT testbeds (testbed+)>

<!ELEMENT testbed (tests)>
<!ATTLIST testbed  n CDATA #IMPLIED>

<!ELEMENT tests (test+)>

<!ELEMENT test (sourceInput, targetOutput)>
<!ATTLIST test id CDATA #IMPLIED 
               is_valid (yes|no) #IMPLIED
               invalidReason CDATA #IMPLIED> 
 
<!ELEMENT sourceInput (lexicalUnits)>
<!ATTLIST sourceInput origin CDATA #IMPLIED> 

<!ELEMENT lexicalUnits (lexicalUnit+)>

<!ELEMENT lexicalUnit (headWord, senseNum, grammaticalCategoryTag, otherTags)>

<!ELEMENT headWord (#PCDATA)>

<!ELEMENT senseNum (#PCDATA)>

<!ELEMENT grammaticalCategoryTag (#PCDATA)>

<!ELEMENT otherTags (tag*)>

<!ELEMENT tag (#PCDATA)>

<!ELEMENT targetOutput (expectedResult, actualResult)>

<!ELEMENT expectedResult (#PCDATA)>

<!ELEMENT actualResult EMPTY>

=== rmlockwood/FLExTrans/XXEaddon/FLExTransTestbedXMLmind/templates/minimalTestbed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransTestbed PUBLIC "-//XMLmind//DTD FLExTransTestbed//EN"
"FLExTransTestbed.dtd">
<FLExTransTestbed source_direction="ltr">
	<testbeds>
		<testbed n="default">
			<tests>
				<test id="123" is_valid="yes">
					<sourceInput origin="Sample">
						<lexicalUnits>
							<lexicalUnit>
								<headWord>sample1</headWord>
								<senseNum>1</senseNum>
								<grammaticalCategoryTag>xyz</grammaticalCategoryTag>
								<otherTags />
							</lexicalUnit>
						</lexicalUnits>
					</sourceInput>
					<targetOutput>
						<expectedResult>My result.</expectedResult>
						<actualResult />
					</targetOutput>
				</test>
			</tests>
		</testbed>
	</testbeds>
</FLExTransTestbed>
