=== rmlockwood/FLExTrans/Rule Assistant/FLExTransRuleGenerator.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT FLExTransRuleGenerator (FLExTransRule)+ >

<!ELEMENT FLExTransRule (source, target)>
<!ATTLIST FLExTransRule
  name CDATA #REQUIRED
>

<!ELEMENT source (phrase) >

<!ELEMENT target (phrase) >
 
<!ELEMENT phrase (word)+ >

<!ELEMENT word (affixes*, features*) >
<!ATTLIST word
  id CDATA #REQUIRED
  category CDATA #IMPLIED
  head (yes | no) "no"
>

<!ELEMENT features (feature)+ >

<!ELEMENT feature EMPTY >
<!ATTLIST feature
  match CDATA #REQUIRED
  label CDATA #REQUIRED
>

<!ELEMENT affixes (affix)+ >

<!ELEMENT affix (features*) >
<!ATTLIST affix
  type (prefix | suffix) "suffix"
>

=== rmlockwood/FLExTrans/Rule Assistant/Ex1c_Indef-Noun.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC "-//XMLmind//DTD FLExTransRuleGenerator//EN"
"FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator
><FLExTransRule
name="Indefinite - Noun (2 feature agreements)"
><source
><phrase
><word
category="indef"
id="1"
></word
><word
category="n"
id="2"
></word
></phrase
></source
><target
><phrase
><word
head="no"
id="1"
><affixes
><affix
type="suffix"
><features
><feature
label="gender"
match="α"
></feature
></features
></affix
><affix
type="suffix"
><features
><feature
label="number"
match="β"
></feature
></features
></affix
></affixes
></word
><word
head="yes"
id="2"
><affixes
><affix
type="suffix"
><features
><feature
label="number"
match="β"
></feature
></features
></affix
></affixes
><features
><feature
label="gender"
match="α"
></feature
></features
></word
></phrase
></target
></FLExTransRule
></FLExTransRuleGenerator
>
