=== rmlockwood/FLExTrans/XXEaddon/FLExTransRuleGeneratorXMLmind/dtds/FLExTransRuleGenerator.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT FLExTransRuleGenerator (DisjointFeatureSets, FLExTransRules) >
<!ATTLIST FLExTransRuleGenerator
    overwrite_rules (yes | no) "yes"
>
<!ELEMENT  FLExTransRules (FLExTransRule+)>

<!ELEMENT DisjointFeatureSets (DisjointFeatureSet*) >
<!ELEMENT DisjointFeatureSet (DisjointFeatureValuePairings)>
<!ATTLIST DisjointFeatureSet
    language (source | target) "target"
    disjoint_name CDATA #REQUIRED
    co_feature_name CDATA #REQUIRED
>
<!ELEMENT DisjointFeatureValuePairings (DisjointFeatureValuePairing, DisjointFeatureValuePairing+)>
<!ELEMENT DisjointFeatureValuePairing EMPTY>
<!ATTLIST DisjointFeatureValuePairing
  flex_feature_name CDATA #REQUIRED
  co_feature_value CDATA #REQUIRED
>

<!ELEMENT FLExTransRule (Description, Source, Target)>
<!ATTLIST FLExTransRule
  name CDATA #REQUIRED
  create_permutations (yes | no) "no"
>

<!ELEMENT Description (#PCDATA) >

<!ELEMENT Source (Phrase) >

<!ELEMENT Target (Phrase) >
 
<!ELEMENT Phrase (Words) >

<!ELEMENT Words (Word+) >

<!ELEMENT Word (Features*, Affixes*) >
<!ATTLIST Word
  id CDATA #REQUIRED
  category CDATA #IMPLIED
  head (yes | no) "no"
>

<!ELEMENT Features (Feature)* >

<!ELEMENT Feature EMPTY >
<!ATTLIST Feature
  match CDATA #REQUIRED
  label CDATA #REQUIRED
  ranking CDATA #REQUIRED
  unmarked_default CDATA #REQUIRED
  value CDATA #REQUIRED
>

<!ELEMENT Affixes (Affix)* >

<!ELEMENT Affix (Features*) >
<!ATTLIST Affix
  type (prefix | suffix) "suffix"
>

=== rmlockwood/FLExTrans/Rule Assistant/Ex4b_Indef-Adj-Noun.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC "-//XMLmind//DTD FLExTransRuleGenerator//EN"
"FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator
><FLExTransRules
><FLExTransRule
name="Indefinite - Adjective - Noun"
><Source
><Phrase
><Words
><Word
category="indef"
head="no"
id="1"
><Features
></Features
><Affixes
></Affixes
></Word
><Word
category="adj"
head="no"
id="2"
><Features
></Features
><Affixes
></Affixes
></Word
><Word
category="n"
head="no"
id="3"
><Features
></Features
><Affixes
></Affixes
></Word
></Words
></Phrase
></Source
><Target
><Phrase
><Words
><Word
category=""
head="no"
id="1"
><Features
></Features
><Affixes
><Affix
type="suffix"
><Features
><Feature
label="gender"
match="α"
></Feature
></Features
></Affix
><Affix
type="suffix"
><Features
><Feature
label="number"
match="β"
></Feature
></Features
></Affix
></Affixes
></Word
><Word
category=""
head="yes"
id="3"
><Features
><Feature
label="gender"
match="α"
></Feature
></Features
><Affixes
><Affix
type="suffix"
><Features
><Feature
label="number"
match="β"
></Feature
></Features
></Affix
></Affixes
></Word
><Word
category=""
head="no"
id="2"
><Features
></Features
><Affixes
><Affix
type="suffix"
><Features
><Feature
label="gender"
match="α"
></Feature
></Features
></Affix
><Affix
type="suffix"
><Features
><Feature
label="number"
match="β"
></Feature
></Features
></Affix
></Affixes
></Word
></Words
></Phrase
></Target
></FLExTransRule
></FLExTransRules
></FLExTransRuleGenerator
>

=== rmlockwood/FLExTrans/Dev/TestRuleAssistant/Rule Assistant/SplitBantuMany.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC " -//XMLmind//DTD FLExTransRuleGenerator//EN"
"FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator>
	<DisjointFeatureSets>
		<DisjointFeatureSet co_feature_name="number" language="target" disjoint_name="BantuNounClass">
			<DisjointFeatureValuePairings>
				<DisjointFeatureValuePairing co_feature_value="sg" flex_feature_name="BantuSG"/>
				<DisjointFeatureValuePairing co_feature_value="pl" flex_feature_name="BantuPL"/>
				<DisjointFeatureValuePairing co_feature_value="many" flex_feature_name="BantuMany"/>
			</DisjointFeatureValuePairings>
		</DisjointFeatureSet>
	</DisjointFeatureSets>
	<FLExTransRules>
		<FLExTransRule name="Noun" create_permutations="no" bantu="yes">
			<Source>
				<Phrase>
					<Words>
						<Word category="n" head="no" id="1">
							<Features/>
							<Affixes/>
						</Word>
					</Words>
				</Phrase>
			</Source>
			<Target>
				<Phrase>
					<Words>
						<Word category="" head="yes" id="1">
							<Features>
								<Feature label="BantuNounClass" match="α"/>
							</Features>
							<Affixes>
								<Affix type="prefix">
									<Features>
										<Feature label="BantuNounClass" match="α"/>
									</Features>
								</Affix>
							</Affixes>
						</Word>
					</Words>
				</Phrase>
			</Target>
		</FLExTransRule>
		<FLExTransRule name="Noun Adj" create_permutations="no">
			<Source>
				<Phrase>
					<Words>
						<Word category="n" head="no" id="1">
							<Features/>
							<Affixes/>
						</Word>
						<Word category="adj" head="no" id="2">
							<Features/>
							<Affixes/>
						</Word>
					</Words>
				</Phrase>
			</Source>
			<Target>
				<Phrase>
					<Words>
						<Word category="" head="yes" id="1">
							<Features>
								<Feature label="BantuNounClass" match="α"/>
							</Features>
							<Affixes>
								<Affix type="prefix">
									<Features>
										<Feature label="BantuNounClass" match="α"/>
									</Features>
								</Affix>
							</Affixes>
						</Word>
						<Word category="" head="no" id="2">
							<Features>
							</Features>
							<Affixes>
								<Affix type="prefix">
									<Features>
										<Feature label="BantuNounClass" match="α"/>
									</Features>
								</Affix>
							</Affixes>
						</Word>
					</Words>
				</Phrase>
			</Target>
		</FLExTransRule>
	</FLExTransRules>
</FLExTransRuleGenerator>

=== rmlockwood/FLExTrans/Rule Assistant/SpanishFrenchRev2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC " -//XMLmind//DTD FLExTransRuleGenerator//EN"
"FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator>
	<DisjointFeatureSets/>
	<FLExTransRules>
		<FLExTransRule name="Def Adj N" create_permutations="yes">
			<Description/>
			<Source>
				<Phrase>
					<Words>
						<Word category="def" head="no" id="3">
							<Features/>
							<Affixes/>
						</Word>
						<Word category="n" head="no" id="1">
							<Features/>
							<Affixes/>
						</Word>
						<Word category="adj" head="no" id="2">
							<Features/>
							<Affixes/>
						</Word>
					</Words>
				</Phrase>
			</Source>
			<Target>
				<Phrase>
					<Words>
						<Word category="" head="no" id="3">
							<Features>
								<Feature label="gender" match="α" ranking="2" unmarked_default="" value=""/>
								<Feature label="number" match="β" ranking="1" unmarked_default="" value=""/>
							</Features>
							<Affixes/>
						</Word>
						<Word category="" head="no" id="2">
							<Features/>
							<Affixes>
								<Affix type="suffix">
									<Features>
										<Feature label="gender" match="α" ranking="0" unmarked_default="m" value=""/>
									</Features>
								</Affix>
								<Affix type="suffix">
									<Features>
										<Feature label="number" match="β" ranking="0" unmarked_default="" value=""/>
									</Features>
								</Affix>
							</Affixes>
						</Word>
						<Word category="" head="yes" id="1">
							<Features>
								<Feature label="gender" match="α" ranking="0" unmarked_default="" value=""/>
							</Features>
							<Affixes>
								<Affix type="suffix">
									<Features>
										<Feature label="number" match="β" ranking="0" unmarked_default="sg" value=""/>
									</Features>
								</Affix>
							</Affixes>
						</Word>
					</Words>
				</Phrase>
			</Target>
		</FLExTransRule>
		<FLExTransRule name="Indf Adj N" create_permutations="no">
			<Description/>
			<Source>
				<Phrase>
					<Words>
						<Word category="indf" head="no" id="1">
							<Features/>
							<Affixes/>
						</Word>
						<Word category="n" head="no" id="2">
							<Features/>
							<Affixes/>
						</Word>
						<Word category="adj" head="no" id="3">
							<Features/>
							<Affixes/>
						</Word>
					</Words>
				</Phrase>
			</Source>
			<Target>
				<Phrase>
					<Words>
						<Word category="" head="no" id="1">
							<Features>
								<Feature label="gender" match="α" ranking="2" unmarked_default="" value=""/>
								<Feature label="number" match="β" ranking="1" unmarked_default="" value=""/>
							</Features>
							<Affixes/>
						</Word>
						<Word category="" head="no" id="3">
							<Features/>
							<Affixes>
								<Affix type="suffix">
									<Features>
										<Feature label="gender" match="α" ranking="0" unmarked_default="m" value=""/>
									</Features>
								</Affix>
								<Affix type="suffix">
									<Features>
										<Feature label="number" match="β" ranking="0" unmarked_default="" value=""/>
									</Features>
								</Affix>
							</Affixes>
						</Word>
						<Word category="" head="yes" id="2">
							<Features>
								<Feature label="gender" match="α" ranking="0" unmarked_default="" value=""/>
							</Features>
							<Affixes>
								<Affix type="suffix">
									<Features>
										<Feature label="number" match="β" ranking="0" unmarked_default="sg" value=""/>
									</Features>
								</Affix>
							</Affixes>
						</Word>
					</Words>
				</Phrase>
			</Target>
		</FLExTransRule>
		<FLExTransRule name="Indf N" create_permutations="no">
			<Description/>
			<Source>
				<Phrase>
					<Words>
						<Word category="indf" head="no" id="1">
							<Features/>
							<Affixes/>
						</Word>
						<Word category="n" head="no" id="2">
							<Features/>
							<Affixes/>
						</Word>
					</Words>
				</Phrase>
			</Source>
			<Target>
				<Phrase>
					<Words>
						<Word category="" head="no" id="1">
							<Features>
								<Feature label="gender" match="α" ranking="2" unmarked_default="" value=""/>
								<Feature label="number" match="β" ranking="1" unmarked_default="" value=""/>
							</Features>
							<Affixes/>
						</Word>
						<Word category="" head="yes" id="2">
							<Features>
								<Feature label="gender" match="α" ranking="0" unmarked_default="" value=""/>
							</Features>
							<Affixes>
								<Affix type="suffix">
									<Features>
										<Feature label="number" match="β" ranking="0" unmarked_default="sg" value=""/>
									</Features>
								</Affix>
							</Affixes>
						</Word>
					</Words>
				</Phrase>
			</Target>
		</FLExTransRule>
	</FLExTransRules>
</FLExTransRuleGenerator>

=== rmlockwood/FLExTrans/XXEaddon/FLExTransRuleGeneratorXMLmind/templates/minimalRuleGenerator.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC "-//XMLmind//DTD FLExTransRuleGenerator//EN"
"FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator>
	<FLExTransRules>
		<FLExTransRule name="test rule">
			<Source>
				<Phrase>
					<Words>
						<Word id="1" category="det">
						</Word>
						<Word id="2" category="n">
						</Word>
					</Words>
				</Phrase>
			</Source>
			<Target>
				<Phrase>
					<Words>
						<Word id="2" head="yes">
		  				<Features>
		  				  <Feature match="α" label="gender">
		  				   </Feature>
		  				</Features>
						</Word>
						<Word id="1" head="no">
		  				<Affixes>
		  				  <Affix type="suffix">
		      				<Features>
		      				  <Feature match="α" label="gender">
		      				   </Feature>
		      				</Features>
		  				  </Affix>
		  				</Affixes>
						</Word>
					</Words>
				</Phrase>
			</Target>
		</FLExTransRule>
	</FLExTransRules>
</FLExTransRuleGenerator>

=== rmlockwood/FLExTrans/TOFTinstall/WorkProjs/Ejagham-Ejagham Demo/Output/RuleAssistantRules.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC " -//XMLmind//DTD FLExTransRuleGenerator//EN"
"FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator overwrite_rules="yes">
    <DisjointFeatureSets>
        <DisjointFeatureSet co_feature_name="number" language="target" disjoint_name="BantuNounGender">
            <DisjointFeatureValuePairings>
                <DisjointFeatureValuePairing co_feature_value="sg" flex_feature_name="BantuSg"/>
                <DisjointFeatureValuePairing co_feature_value="pl" flex_feature_name="BantuPl"/>
            </DisjointFeatureValuePairings>
        </DisjointFeatureSet>
    </DisjointFeatureSets>
    <FLExTransRules>
        <FLExTransRule name="N Num=one" create_permutations="no">
            <Description>don't use disjoint for the number since the number one is mapped as a whole</Description>
            <Source>
                <Phrase>
                    <Words>
                        <Word category="n" head="no" id="1">
                            <Features/>
                            <Affixes/>
                        </Word>
                        <Word category="num" head="no" id="2">
                            <Features/>
                            <Affixes/>
                        </Word>
                    </Words>
                </Phrase>
            </Source>
            <Target>
                <Phrase>
                    <Words>
                        <Word category="" head="yes" id="1">
                            <Features>
<Feature label="BantuSg" match="α" ranking="0" unmarked_default="" value=""/>
<Feature label="BantuNounGender" match="β" ranking="0" unmarked_default="" value=""/>
                            </Features>
                            <Affixes>
<Affix type="prefix">
    <Features>
        <Feature label="BantuNounGender" match="β" ranking="0" unmarked_default="" value=""/>
    </Features>
</Affix>
                            </Affixes>
                        </Word>
                        <Word category="" head="no" id="2">
                            <Features>
<Feature label="BantuSg" match="α" ranking="0" unmarked_default="" value=""/>
                            </Features>
                            <Affixes/>
                        </Word>
                    </Words>
                </Phrase>
            </Target>
        </FLExTransRule>
        <FLExTransRule name="N Num" create_permutations="with_head">
            <Description></Description>
            <Source>
                <Phrase>
                    <Words>
                        <Word category="n" head="no" id="1">
                            <Features/>
                            <Affixes/>
                        </Word>
                        <Word category="num" head="no" id="2">
                            <Features/>
                            <Affixes/>
                        </Word>
                    </Words>
                </Phrase>
            </Source>
            <Target>
                <Phrase>
                    <Words>
                        <Word category="" head="yes" id="1">
                            <Features>
<Feature label="BantuNounGender" match="α" ranking="0" unmarked_default="" value=""/>
                            </Features>
                            <Affixes>
<Affix type="prefix">
    <Features>
        <Feature label="BantuNounGender" match="α" ranking="0" unmarked_default="" value=""/>
    </Features>
</Affix>
                            </Affixes>
                        </Word>
                        <Word category="" head="no" id="2">
                            <Features/>
                            <Affixes>
<Affix type="prefix">
    <Features>
        <Feature label="BantuNounGender" match="α" ranking="0" unmarked_default="" value=""/>
    </Features>
</Affix>
                            </Affixes>
                        </Word>
                    </Words>
                </Phrase>
            </Target>
        </FLExTransRule>
    </FLExTransRules>
</FLExTransRuleGenerator>

=== rmlockwood/FLExTrans/Rule Assistant/Ex4a_Def-Adj-Noun.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC "-//XMLmind//DTD FLExTransRuleGenerator//EN"
"FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator
><FLExTransRules
><FLExTransRule
name="Definite - Adjective - Noun"
><Source
><Phrase
><Words
><Word
category="def"
id="1"
></Word
><Word
category="adj"
id="2"
></Word
><Word
category="n"
id="3"
></Word
></Words
></Phrase
></Source
><Target
><Phrase
><Words
><Word
head="no"
id="1"
><Features
><Feature
label="gender"
match="α"
></Feature
><Feature
label="number"
match="β"
></Feature
></Features
></Word
><Word
head="yes"
id="3"
><Features
><Feature
label="gender"
match="α"
></Feature
></Features
><Affixes
><Affix
type="suffix"
><Features
><Feature
label="number"
match="β"
></Feature
></Features
></Affix
></Affixes
></Word
><Word
head="no"
id="2"
><Affixes
><Affix
type="suffix"
><Features
><Feature
label="gender"
match="α"
></Feature
></Features
></Affix
><Affix
type="suffix"
><Features
><Feature
label="number"
match="β"
></Feature
></Features
></Affix
></Affixes
></Word
></Words
></Phrase
></Target
></FLExTransRule
></FLExTransRules
></FLExTransRuleGenerator
>

=== rmlockwood/FLExTrans/Rule Assistant/insert_word.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC " -//XMLmind//DTD FLExTransRuleGenerator//EN"
"FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator>
	<FLExTransRules>
		<FLExTransRule name="Def (remove src word 1)" create_permutations="no">
			<Source>
				<Phrase>
					<Words>
						<Word category="n" head="no" id="2">
							<Features/>
							<Affixes>
								<Affix type="suffix">
									<Features>
										<Feature label="definiteness" match="" ranking="0" unmarked_default="" value="defid"/>
										<Feature label="number" match="β" ranking="0" unmarked_default="" value=""/>
									</Features>
								</Affix>
							</Affixes>
						</Word>
					</Words>
				</Phrase>
			</Source>
			<Target>
				<Phrase>
					<Words>
						<Word category="def" head="no" id="1">
							<Features>
								<Feature label="definiteness" match="" ranking="0" unmarked_default="" value="defid"/>
								<Feature label="gender" match="α" ranking="0" unmarked_default="" value=""/>
								<Feature label="number" match="β" ranking="0" unmarked_default="" value=""/>
							</Features>
							<Affixes/>
						</Word>
						<Word category="" head="yes" id="2">
							<Features>
								<Feature label="gender" match="α" ranking="0" unmarked_default="" value=""/>
							</Features>
							<Affixes/>
						</Word>
					</Words>
				</Phrase>
			</Target>
		</FLExTransRule>
	</FLExTransRules>
</FLExTransRuleGenerator>

=== rmlockwood/FLExTrans/Rule Assistant/Ex1a_Def-Noun.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC "-//XMLmind//DTD FLExTransRuleGenerator//EN"
"FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator
><FLExTransRules
><FLExTransRule
name="Definite - Noun"
><Source
><Phrase
><Words
><Word
category="def"
id="1"
></Word
><Word
category="n"
id="2"
></Word
></Words
></Phrase
></Source
><Target
><Phrase
><Words
><Word
head="no"
id="1"
><Features
><Feature
label="gender"
match="α"
></Feature
></Features
></Word
><Word
head="yes"
id="2"
><Features
><Feature
label="gender"
match="α"
></Feature
></Features
></Word
></Words
></Phrase
></Target
></FLExTransRule
></FLExTransRules
></FLExTransRuleGenerator
>
