=== rmlockwood/FLExTrans/XXEaddon/FLExTransRuleGeneratorXMLmind/dtds/FLExTransRuleGenerator.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT FLExTransRuleGenerator (DisjointFeatureSets, FLExTransRules) >
<!ATTLIST FLExTransRuleGenerator
    overwrite_rules (yes | no) "yes"
>
<!ELEMENT  FLExTransRules (FLExTransRule+)>

<!ELEMENT DisjointFeatureSets (DisjointFeatureSet*) >
<!ELEMENT DisjointFeatureSet (DisjointFeatureValuePairings)>
<!ATTLIST DisjointFeatureSet
    language (source | target) "target"
    disjoint_name CDATA #REQUIRED
    co_feature_name CDATA #REQUIRED
>
<!ELEMENT DisjointFeatureValuePairings (DisjointFeatureValuePairing, DisjointFeatureValuePairing+)>
<!ELEMENT DisjointFeatureValuePairing EMPTY>
<!ATTLIST DisjointFeatureValuePairing
  flex_feature_name CDATA #REQUIRED
  co_feature_value CDATA #REQUIRED
>

<!ELEMENT FLExTransRule (Description, Source, Target)>
<!ATTLIST FLExTransRule
  name CDATA #REQUIRED
  create_permutations (yes | no) "no"
>

<!ELEMENT Description (#PCDATA) >

<!ELEMENT Source (Phrase) >

<!ELEMENT Target (Phrase) >
 
<!ELEMENT Phrase (Words) >

<!ELEMENT Words (Word+) >

<!ELEMENT Word (Features*, Affixes*) >
<!ATTLIST Word
  id CDATA #REQUIRED
  category CDATA #IMPLIED
  head (yes | no) "no"
>

<!ELEMENT Features (Feature)* >

<!ELEMENT Feature EMPTY >
<!ATTLIST Feature
  match CDATA #REQUIRED
  label CDATA #REQUIRED
  ranking CDATA #REQUIRED
  unmarked_default CDATA #REQUIRED
  value CDATA #REQUIRED
>

<!ELEMENT Affixes (Affix)* >

<!ELEMENT Affix (Features*) >
<!ATTLIST Affix
  type (prefix | suffix) "suffix"
>

=== rmlockwood/FLExTrans/Rule Assistant/PatternFeature.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC " -//XMLmind//DTD FLExTransRuleGenerator//EN"
"FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator>
    <FLExTransRules>
        <FLExTransRule name="Def" create_permutations="no">
            <Source>
                <Phrase>
                    <Words>
                        <Word category="def" head="no" id="1">
                            <Features>
<Feature label="definiteness" match="" ranking="0" unmarked_default="" value="defid"/>
<Feature label="number" match="β" ranking="0" unmarked_default="" value=""/>
                            </Features>
                            <Affixes/>
                        </Word>
                        <Word category="n" head="no" id="2">
                            <Features/>
                            <Affixes/>
                        </Word>
                    </Words>
                </Phrase>
            </Source>
            <Target>
                <Phrase>
                    <Words>
                        <Word category="" head="yes" id="2">
                            <Features/>
                            <Affixes>
<Affix type="suffix">
    <Features>
        <Feature label="number" match="β" ranking="0" unmarked_default="" value=""/>
    </Features>
</Affix>
<Affix type="suffix">
    <Features>
        <Feature label="definiteness" match="" ranking="0" unmarked_default="" value="defid"/>
    </Features>
</Affix>
                            </Affixes>
                        </Word>
                    </Words>
                </Phrase>
            </Target>
        </FLExTransRule>
    </FLExTransRules>
</FLExTransRuleGenerator>

=== rmlockwood/FLExTrans/Dev/TestRuleAssistant/Rule Assistant/GermanEnglishDoubleDefault.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC " -//XMLmind//DTD FLExTransRuleGenerator//EN"
"FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator>
    <FLExTransRules>
        <FLExTransRule name="def n simple" create_permutations="no">
            <Source>
                <Phrase>
                    <Words>
                        <Word category="n" head="no" id="1">
                            <Features/>
                            <Affixes/>
                        </Word>
                    </Words>
                </Phrase>
            </Source>
            <Target>
                <Phrase>
                    <Words>
                        <Word category="" head="yes" id="1">
                            <Features/>
                            <Affixes>
								<Affix type="suffix">
									<Features>
        <Feature label="number" match="β" ranking="0" unmarked_default="sg" value=""/>
        <Feature label="case" match="γ" ranking="0" unmarked_default="nom" value=""/>
									</Features>
								</Affix>
                            </Affixes>
                        </Word>
                    </Words>
                </Phrase>
            </Target>
        </FLExTransRule>
    </FLExTransRules>
</FLExTransRuleGenerator>

=== rmlockwood/FLExTrans/Rule Assistant/ranking.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC "-//XMLmind//DTD FLExTransRuleGenerator//EN" "FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator>
  <FLExTransRules>
    <FLExTransRule name="Def N">
      <Source>
        <Phrase>
          <Words>
            <Word category="def" id="1">
            </Word>
            <Word category="n" id="2">
            </Word>
          </Words>
        </Phrase>
      </Source>
      <Target>
        <Phrase>
          <Words>
            <Word head="no" id="1">
              <Features>
                <Feature label="number" match="n" ranking="1"/>
                <Feature label="gender" match="g" ranking="2"/>
              </Features>
            </Word>
            <Word head="yes" id="2">
				<Features>
					<Feature label="gender" match="g"/>
				</Features>
				<Affixes>
					<Affix type="suffix">
						<Features>
							<Feature label="number" match="n"/>
						</Features>
					</Affix>
				</Affixes>
            </Word>
          </Words>
        </Phrase>
      </Target>
    </FLExTransRule>
  </FLExTransRules>
</FLExTransRuleGenerator>

=== rmlockwood/FLExTrans/Dev/TestRuleAssistant/Rule Assistant/EnglishGermanTripleRankingPartialDefault.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC " -//XMLmind//DTD FLExTransRuleGenerator//EN"
"FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator>
    <FLExTransRules>
        <FLExTransRule name="def adj n" create_permutations="yes">
            <Description>number is rank 1 because die (pl) is used often for all genders
case is rank 2 because for a case often the form is the same for all genders </Description>
            <Source>
                <Phrase>
                    <Words>
                        <Word category="def" head="no" id="1">
                            <Features/>
                            <Affixes/>
                        </Word>
                        <Word category="adj" head="no" id="2">
                            <Features/>
                            <Affixes/>
                        </Word>
                        <Word category="n" head="no" id="3">
                            <Features/>
                            <Affixes/>
                        </Word>
                    </Words>
                </Phrase>
            </Source>
            <Target>
                <Phrase>
                    <Words>
                        <Word category="" head="no" id="1">
                            <Features>
<Feature label="number" match="β" ranking="1" unmarked_default="" value=""/>
<Feature label="gender" match="α" ranking="3" unmarked_default="" value=""/>
<Feature label="case" match="γ" ranking="2" unmarked_default="" value=""/>
                            </Features>
                            <Affixes/>
                        </Word>
                        <Word category="" head="no" id="2">
                            <Features/>
                            <Affixes>
<Affix type="suffix">
    <Features>
        <Feature label="gender" match="α" ranking="3" unmarked_default="" value=""/>
        <Feature label="number" match="β" ranking="1" unmarked_default="" value=""/>
        <Feature label="case" match="γ" ranking="2" unmarked_default="" value=""/>
    </Features>
</Affix>
                            </Affixes>
                        </Word>
                        <Word category="" head="yes" id="3">
                            <Features>
<Feature label="gender" match="α" ranking="0" unmarked_default="" value=""/>
                            </Features>
                            <Affixes>
<Affix type="suffix">
    <Features>
        <Feature label="case" match="γ" ranking="2" unmarked_default="nom" value=""/>
        <Feature label="gender" match="α" ranking="3" unmarked_default="" value=""/>
        <Feature label="number" match="β" ranking="1" unmarked_default="sg" value=""/>
    </Features>
</Affix>
                            </Affixes>
                        </Word>
                    </Words>
                </Phrase>
            </Target>
        </FLExTransRule>
    </FLExTransRules>
</FLExTransRuleGenerator>

=== rmlockwood/FLExTrans/Rule Assistant/Ex3_Adj-Noun.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC "-//XMLmind//DTD FLExTransRuleGenerator//EN"
"FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator
><FLExTransRules
><FLExTransRule
name="Adjective - Noun (2 Feature agreements)"
><Source
><Phrase
><Words
><Word
category="adj"
id="1"
></Word
><Word
category="n"
id="2"
></Word
></Words
></Phrase
></Source
><Target
><Phrase
><Words
><Word
head="yes"
id="2"
><Features
><Feature
label="gender"
match="α"
></Feature
></Features
><Affixes
><Affix
type="suffix"
><Features
><Feature
label="number"
match="β"
></Feature
></Features
></Affix
></Affixes
></Word
><Word
head="no"
id="1"
><Affixes
><Affix
type="suffix"
><Features
><Feature
label="gender"
match="α"
></Feature
></Features
></Affix
><Affix
type="suffix"
><Features
><Feature
label="number"
match="β"
></Feature
></Features
></Affix
></Affixes
></Word
></Words
></Phrase
></Target
></FLExTransRule
></FLExTransRules
></FLExTransRuleGenerator
>

=== rmlockwood/FLExTrans/RuleAssistantRules.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC " -//XMLmind//DTD FLExTransRuleGenerator//EN"
"FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator overwrite_rules="yes">
    <DisjointFeatureSets/>
    <FLExTransRules>
        <FLExTransRule name="Indef N" create_permutations="not_head">
            <Description>The indefinite article should agree in number and gender with the head noun.</Description>
            <Source>
                <Phrase>
                    <Words>
                        <Word category="indf" head="no" id="1">
                            <Features/>
                            <Affixes/>
                        </Word>
                        <Word category="n" head="no" id="2">
                            <Features/>
                            <Affixes/>
                        </Word>
                    </Words>
                </Phrase>
            </Source>
            <Target>
                <Phrase>
                    <Words>
                        <Word category="" head="no" id="1">
                            <Features/>
                            <Affixes>
<Affix type="suffix">
    <Features>
        <Feature label="gender" match="α" ranking="0" unmarked_default="" value=""/>
    </Features>
</Affix>
<Affix type="suffix">
    <Features>
        <Feature label="number" match="β" ranking="0" unmarked_default="" value=""/>
    </Features>
</Affix>
                            </Affixes>
                        </Word>
                        <Word category="" head="yes" id="2">
                            <Features>
<Feature label="gender" match="α" ranking="0" unmarked_default="" value=""/>
                            </Features>
                            <Affixes>
<Affix type="suffix">
    <Features>
        <Feature label="number" match="β" ranking="0" unmarked_default="" value=""/>
    </Features>
</Affix>
                            </Affixes>
                        </Word>
                    </Words>
                </Phrase>
            </Target>
        </FLExTransRule>
        <FLExTransRule name="Indef Adj N" create_permutations="with_head">
            <Description>The indefinite article should agree in number and gender with the head noun. Also the adjective should agree in number and gender with the noun.</Description>
            <Source>
                <Phrase>
                    <Words>
                        <Word category="indf" head="no" id="1">
                            <Features/>
                            <Affixes/>
                        </Word>
                        <Word category="adj" head="no" id="3">
                            <Features/>
                            <Affixes/>
                        </Word>
                        <Word category="n" head="no" id="2">
                            <Features/>
                            <Affixes/>
                        </Word>
                    </Words>
                </Phrase>
            </Source>
            <Target>
                <Phrase>
                    <Words>
                        <Word category="" head="no" id="1">
                            <Features/>
                            <Affixes>
<Affix type="suffix">
    <Features>
        <Feature label="gender" match="α" ranking="0" unmarked_default="" value=""/>
    </Features>
</Affix>
<Affix type="suffix">
    <Features>
        <Feature label="number" match="β" ranking="0" unmarked_default="" value=""/>
    </Features>
</Affix>
                            </Affixes>
                        </Word>
                        <Word category="" head="yes" id="2">
                            <Features>
<Feature label="gender" match="α" ranking="0" unmarked_default="" value=""/>
                            </Features>
                            <Affixes>
<Affix type="suffix">
    <Features>
        <Feature label="number" match="β" ranking="0" unmarked_default="" value=""/>
    </Features>
</Affix>
                            </Affixes>
                        </Word>
                        <Word category="" head="no" id="3">
                            <Features/>
                            <Affixes>
<Affix type="suffix">
    <Features>
        <Feature label="gender" match="α" ranking="0" unmarked_default="" value=""/>
    </Features>
</Affix>
<Affix type="suffix">
    <Features>
        <Feature label="number" match="β" ranking="0" unmarked_default="" value=""/>
    </Features>
</Affix>
                            </Affixes>
                        </Word>
                    </Words>
                </Phrase>
            </Target>
        </FLExTransRule>
    </FLExTransRules>
</FLExTransRuleGenerator>

=== rmlockwood/FLExTrans/Rule Assistant/Ex2_Adj-Noun.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC "-//XMLmind//DTD FLExTransRuleGenerator//EN"
"FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator
><FLExTransRules
><FLExTransRule
name="Adjective - Noun"
><Source
><Phrase
><Words
><Word
category="adj"
id="1"
></Word
><Word
category="n"
id="2"
></Word
></Words
></Phrase
></Source
><Target
><Phrase
><Words
><Word
head="yes"
id="2"
><Features
><Feature
label="gender"
match="α"
></Feature
></Features
></Word
><Word
head="no"
id="1"
><Affixes
><Affix
type="suffix"
><Features
><Feature
label="gender"
match="α"
></Feature
></Features
></Affix
></Affixes
></Word
></Words
></Phrase
></Target
></FLExTransRule
></FLExTransRules
></FLExTransRuleGenerator
>

=== rmlockwood/FLExTrans/Rule Assistant/SplitBantu.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE FLExTransRuleGenerator PUBLIC " -//XMLmind//DTD FLExTransRuleGenerator//EN"
"FLExTransRuleGenerator.dtd">
<FLExTransRuleGenerator SingularClass="BantuSG" PluralClass="BantuPL" MergedClass="BantuNounClass">
	<FLExTransRules>
		<FLExTransRule name="Noun" create_permutations="no" bantu="yes">
			<Source>
				<Phrase>
					<Words>
						<Word category="n" head="no" id="1">
							<Features/>
							<Affixes/>
						</Word>
					</Words>
				</Phrase>
			</Source>
			<Target>
				<Phrase>
					<Words>
						<Word category="" head="yes" id="1">
							<Features>
								<Feature label="BantuNounClass" match="α"/>
							</Features>
							<Affixes>
								<Affix type="prefix">
									<Features>
										<Feature label="BantuNounClass" match="α"/>
									</Features>
								</Affix>
							</Affixes>
						</Word>
					</Words>
				</Phrase>
			</Target>
		</FLExTransRule>
		<FLExTransRule name="Noun Adj" create_permutations="no">
			<Source>
				<Phrase>
					<Words>
						<Word category="n" head="no" id="1">
							<Features/>
							<Affixes/>
						</Word>
						<Word category="adj" head="no" id="2">
							<Features/>
							<Affixes/>
						</Word>
					</Words>
				</Phrase>
			</Source>
			<Target>
				<Phrase>
					<Words>
						<Word category="" head="yes" id="1">
							<Features>
								<Feature label="BantuNounClass" match="α"/>
							</Features>
							<Affixes>
								<Affix type="prefix">
									<Features>
										<Feature label="BantuNounClass" match="α"/>
									</Features>
								</Affix>
							</Affixes>
						</Word>
						<Word category="" head="no" id="2">
							<Features>
							</Features>
							<Affixes>
								<Affix type="prefix">
									<Features>
										<Feature label="BantuNounClass" match="α"/>
									</Features>
								</Affix>
							</Affixes>
						</Word>
					</Words>
				</Phrase>
			</Target>
		</FLExTransRule>
	</FLExTransRules>
</FLExTransRuleGenerator>
